// This file defines all static game data, including character classes, cards (items, spells, monsters, etc.),
// NPC dialogue, skill challenges, and other game constants. It is used exclusively by the server (`server.js`) to populate
// the game world and manage game mechanics. It is not sent to the client.

// This file contains the game data, structured for the server.

let lastId = 0;
const nextId = () => { lastId++; return `card-${lastId}`; };

const classes = {
    Barbarian: { baseHp: 24, baseDamageBonus: 4, baseShieldBonus: 0, baseAp: 3, healthDice: 4, stats: { str: 4, dex: 1, con: 3, int: 0, wis: 0, cha: 1 }, description: "A fierce warrior of primal rage.", abilities: ["Rage", "Reckless Attack"] },
    Cleric:    { baseHp: 20, baseDamageBonus: 1, baseShieldBonus: 3, baseAp: 2, healthDice: 3, stats: { str: 1, dex: 0, con: 2, int: 1, wis: 4, cha: 2 }, description: "A conduit for divine power.", abilities: ["Channel Divinity", "Turn Undead"] },
    Mage:      { baseHp: 18, baseDamageBonus: 1, baseShieldBonus: 2, baseAp: 2, healthDice: 2, stats: { str: 0, dex: 1, con: 1, int: 4, wis: 2, cha: 1 }, description: "Wielder of arcane energies.", abilities: ["Arcane Recovery", "Spell Mastery"] },
    Ranger:    { baseHp: 20, baseDamageBonus: 2, baseShieldBonus: 2, baseAp: 2, healthDice: 3, stats: { str: 1, dex: 4, con: 2, int: 1, wis: 3, cha: 0 }, description: "A peerless hunter and scout.", abilities: ["Favored Enemy", "Hunter's Mark"] },
    Rogue:     { baseHp: 18, baseDamageBonus: 3, baseShieldBonus: 1, baseAp: 3, healthDice: 2, stats: { str: 1, dex: 4, con: 1, int: 2, wis: 0, cha: 3 }, description: "A master of stealth and precision.", abilities: ["Sneak Attack", "Evasion"] },
    Warrior:   { baseHp: 22, baseDamageBonus: 2, baseShieldBonus: 4, baseAp: 3, healthDice: 4, stats: { str: 3, dex: 2, con: 4, int: 0, wis: 1, cha: 1 }, description: "A master of arms and armor.", abilities: ["Second Wind", "Defensive Stance"] },
};

const statusEffectDefinitions = {
    'Poisoned': { trigger: 'start', damage: '1d4', description: 'Takes 1d4 damage at the start of their turn.' },
    'Stunned': { cannotAct: true, description: 'Cannot take actions.' },
    'On Fire': { trigger: 'start', damage: '1d6', description: 'Takes 1d6 damage at the start of their turn.'},
    'Guarded': { rollModifier: 2, description: 'Has +2 to defense rolls.'},
    'Slowed': { rollModifier: -2, description: 'Has -2 to all d20 rolls.'},
    'Drained': { description: 'Starts turn with -1 AP.' },
    'Inspired': { description: 'Feeling motivated, +2 to attack rolls.' },
};

const actionCosts = {
    briefRespite: 1,
    fullRest: 2,
    guard: 1
};

const skillChallenges = [
    {
        id: 'sc-01',
        name: 'Disarm Trapped Chest',
        description: 'You find a heavy, iron-bound chest. The lock looks complex, and you hear a faint clicking from within.',
        skill: 'dex',
        dc: 14,
        successThreshold: 2,
        failureThreshold: 1,
        itemBonus: {
            'Lockpicks & Shims': { rollModifier: 3 },
        },
        success: {
            message: 'With a final *click*, the lock opens and the trap is disarmed! You open the chest to find some loot.',
            reward: { type: 'loot', count: 2 }
        },
        failure: {
            message: 'You hear a loud *SNAP* as the trap springs! A spray of acid shoots out.',
            consequence: { type: 'damage', dice: '2d6', target: 'initiator' }
        }
    },
    {
        id: 'sc-02',
        name: 'Climb a Treacherous Cliff',
        description: 'A steep cliff face blocks your path. The rock is slick with moss and rain.',
        skill: 'str',
        dc: 15,
        successThreshold: 3,
        failureThreshold: 2,
        itemBonus: {
            "Climber's Spikes": { rollModifier: 3 },
            "Sturdy Cord (50 ft)": { rollModifier: 2 }
        },
        success: {
            message: 'After a grueling climb, the whole party reaches the top, revealing a hidden path forward.',
            reward: { type: 'progress', message: 'The path forward is clear.' }
        },
        failure: {
            message: 'The party loses their grip and tumbles down, taking damage and losing time.',
            consequence: { type: 'damage', dice: '2d8', target: 'party' }
        }
    }
];

const npcDialogue = {
    explorer: {
        attack: [
            "Take this, you fiend!",
            "My blade finds its mark!",
            "For the light!",
            "Feel my wrath!",
            "You won't get past me!",
            "Another one for the count!",
            "Let's see how you like this!",
            "Taste steel!",
            "Go back to the shadows!",
            "This ends now!",
            "Feel my steel!",
            "Back to the abyss with you!",
            "Suffer my wrath!",
            "This is for my comrades!",
            "You have no place here!",
        ],
        heal: [
            "Hold on, friend, let me help you.",
            "Feel the light mend your wounds.",
            "By my power, you are healed!",
            "Stay with us! This should help.",
            "A small respite for you.",
            "The gods are with you!",
            "Your wounds are closing.",
            "Don't give up! I'm here.",
            "Let this magic restore you.",
            "You'll be back on your feet in no time.",
            "Let this light restore your strength.",
            "Your vitality returns!",
            "Do not falter! We are with you.",
            "May this aid your recovery.",
            "The magic flows through you, mending your injuries.",
        ],
        onHit: [
            "That one was close!",
            "I won't fall so easily!",
            "A mere scratch!",
            "Is that all you've got?",
            "You'll pay for that!",
            "I've had worse!",
            "A worthy blow, but not enough!",
            "It will take more than that to stop me!",
            "Gah! A lucky shot!",
            "My turn is coming...",
            "A lucky strike!",
            "I can take it!",
            "You'll regret that swing!",
            "Barely felt it!",
            "I'll return this pain tenfold!",
        ],
        utility: [ // New Category
            "Just the tool for the job!",
            "Let's see what this can do.",
            "A clever solution is needed here.",
            "This should even the odds.",
            "Time for a different approach.",
            "I have an idea!",
            "Let me handle this.",
        ]
    },
    dm: {
        worldEvent: [
            "A chill wind blows, bringing a strange scent...",
            "As you step into the forest, the trees seem to lean in, as if to listen.",
            "The ground trembles for a moment, then falls still.",
            "A strange, ethereal light filters through the canopy above.",
            "You hear a distant cry, half-animal, half-human.",
            "The air suddenly grows heavy, thick with unspoken magic.",
            "For a brief second, the world loses its color, turning to shades of gray.",
            "A forgotten melody drifts on the breeze, its source unknown.",
            "The shadows around you seem to deepen and writhe.",
            "An ancient stone nearby begins to hum with a low energy.",
            "A sudden silence falls over the area, the birdsong ceasing abruptly.",
            "The stars above seem to shift into an unfamiliar constellation.",
            "You feel a wave of unseen energy wash over you, leaving a tingling sensation on your skin.",
            "A disembodied whisper seems to echo in the back of your minds, speaking a language you don't understand.",
            "The temperature drops noticeably, and your breath mists in the air.",
            "A flock of black birds takes to the sky in a panic, fleeing from an unseen terror.",
            "The path ahead is suddenly obscured by a thick, rolling fog that appeared from nowhere.",
            "You all share a sudden, vivid vision of a forgotten king on a crumbling throne.",
            "The moon, though it is midday, briefly becomes visible in the sky.",
            "Water in your canteens ripples, despite no one touching them.",
        ],
        playMonster: [
            "From the shadows, a grotesque creature emerges!",
            "You are not alone. Something scuttles toward you...",
            "A roar echoes through the chamber as a beast reveals itself!",
            "The air grows cold as a monster appears before you.",
            "Disturbing the dust, a creature of nightmare lurches into view.",
            "Claws scrape on stone as a horror from the depths crawls into the light.",
            "You've disturbed something. It does not look pleased.",
            "A hulking silhouette blocks your path, its eyes glowing with malice.",
            "The stench of decay precedes a shambling monstrosity.",
            "Bursting from the ground, a creature of earth and rage confronts you!",
            "It unfolds itself from the darkness, a nightmare of claws and teeth.",
            "Your presence has awakened something ancient and hungry.",
            "A chittering sound echoes from the tunnel ahead before a swarm of creatures pours out.",
            "The ground splits open, and a chthonic horror claws its way into the world.",
            "It was not a statue. It was waiting. And now it moves.",
            "A low growl emanates from all around you before a massive beast pads into the light.",
            "The water in the pool churns, and a serpentine creature rises from the depths.",
            "With a sickening crunch of bone, a monstrosity pieced together from fallen warriors stands before you.",
            "You hear a faint giggling, and a small, malicious-looking creature peeks from behind a rock.",
            "This cave is not empty. You have trespassed, and its guardian has come to greet you.",
        ],
        monsterDefeated: [
            "The creature's last breath escapes it in a foul gasp.",
            "The beast falls silent, its reign of terror over.",
            "With a final shudder, the monster collapses into a lifeless heap.",
            "Your foe is vanquished, its dark presence fading from the world.",
            "Victory! The monster lies defeated at your feet.",
            "The monstrosity crumbles to dust, its evil unmade.",
            "A final, agonized cry, and then... silence.",
            "The threat is neutralized. You may proceed.",
            "The creature's lightless eyes stare blankly at the ceiling.",
            "You have overcome the challenge. The beast is no more.",
            "The foul energy that animated it dissipates, leaving only a husk.",
            "Its roar of defiance turns into a pathetic gurgle as it chokes on its own ichor.",
            "The ground is stained with its foul blood as the beast breathes its last.",
            "As it falls, the very air seems to lighten, cleansed of its presence.",
            "The monster's form dissolves into a pool of shimmering, foul-smelling liquid.",
            "Its grip on this world is broken. The creature is gone.",
            "A final, hateful glare, and the light fades from the monster's eyes.",
            "The battle is won. The chamber is quiet once more, save for your heavy breathing.",
            "With a deafening crash, the massive creature topples, shaking the very foundations of the room.",
            "The small, vicious creature gives one last squeal of fury before going still.",
        ],
        environment: [ 
            "The air here is damp and smells of moss and decay.",
            "A faint, rhythmic dripping sound echoes from somewhere deeper in the darkness.",
            "Ancient, faded murals cover the walls, depicting forgotten heroes and their deeds.",
            "The ground is littered with bones, both animal and, alarmingly, humanoid.",
            "A thick, unnatural fog clings to the floor, obscuring your vision.",
            "Torches on the walls flicker, casting long, dancing shadows.",
            "The silence in this chamber is heavy, almost suffocating.",
            "You enter a vast cavern, the ceiling lost in darkness above. The air is cold.",
            "Before you stands an ancient ruin, its stones crumbling with age and choked by vines.",
            "The clearing is eerily quiet, dominated by a single, massive dead tree at its center.",
            "The scent of ozone hangs in the air here, a sure sign of recent, powerful magic.",
        ]
    }
};

const itemCards = [
    { id: nextId(), name: "Purifying Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d6", target: "any-monster", description: "Ranged attack (20/60). Deals 2d6 radiant damage to Undead or Fiends." } },
    { id: nextId(), name: "Purifying Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d6", target: "any-monster", description: "Ranged attack (20/60). Deals 2d6 radiant damage to Undead or Fiends." } },
    { id: nextId(), name: "Purifying Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d6", target: "any-monster", description: "Ranged attack (20/60). Deals 2d6 radiant damage to Undead or Fiends." } },
    { id: nextId(), name: "Everbright Stick", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Emits bright light in a 20 ft radius, and dim light for an additional 20 ft, for 1 hour (2 turns)." } },
    { id: nextId(), name: "Everbright Stick", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Emits bright light in a 20 ft radius, and dim light for an additional 20 ft, for 1 hour (2 turns)." } },
    { id: nextId(), name: "Everbright Stick", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Emits bright light in a 20 ft radius, and dim light for an additional 20 ft, for 1 hour (2 turns)." } },
    { id: nextId(), name: "Combustion Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d4", status: "On Fire", duration: 2, target: "any-monster", description: "Ranged attack (20/60). On hit, target takes 1d4 fire damage immediately and 1d4 fire damage at the start of their turn for 1 minute (1 turn), unless they or an adjacent creature use an action (DC 10 Dexterity Check) to douse the flames." } },
    { id: nextId(), name: "Combustion Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d4", status: "On Fire", duration: 2, target: "any-monster", description: "Ranged attack (20/60). On hit, target takes 1d4 fire damage immediately and 1d4 fire damage at the start of their turn for 1 minute (1 turn), unless they or an adjacent creature use an action (DC 10 Dexterity Check) to douse the flames." } },
    { id: nextId(), name: "Combustion Flask", type: "Consumable", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d4", status: "On Fire", duration: 2, target: "any-monster", description: "Ranged attack (20/60). On hit, target takes 1d4 fire damage immediately and 1d4 fire damage at the start of their turn for 1 minute (1 turn), unless they or an adjacent creature use an action (DC 10 Dexterity Check) to douse the flames." } },
    { id: nextId(), name: "Trail Provisions", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Sustains one creature for one day. Prevents exhaustion from lack of food/water. Multiple uses (e.g., 3-5 uses)." } },
    { id: nextId(), name: "Trail Provisions", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Sustains one creature for one day. Prevents exhaustion from lack of food/water. Multiple uses (e.g., 3-5 uses)." } },
    { id: nextId(), name: "Trail Provisions", type: "Consumable", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Sustains one creature for one day. Prevents exhaustion from lack of food/water. Multiple uses (e.g., 3-5 uses)." } },
    { id: nextId(), name: "Empty Flask", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can hold liquids. Useful for collecting samples or crafting potions (if that mechanic exists)." } },
    { id: nextId(), name: "Empty Flask", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can hold liquids. Useful for collecting samples or crafting potions (if that mechanic exists)." } },
    { id: nextId(), name: "Empty Flask", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can hold liquids. Useful for collecting samples or crafting potions (if that mechanic exists)." } },
    { id: nextId(), name: "Brew of Silent Movement", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Dexterity (Stealth) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Brew of Silent Movement", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Dexterity (Stealth) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Brew of Silent Movement", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Dexterity (Stealth) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Brew of Unseen Passage", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Become invisible for 1 minute (1 turn). The effect ends if you attack or cast a spell." } },
    { id: nextId(), name: "Brew of Unseen Passage", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Become invisible for 1 minute (1 turn). The effect ends if you attack or cast a spell." } },
    { id: nextId(), name: "Brew of Unseen Passage", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Become invisible for 1 minute (1 turn). The effect ends if you attack or cast a spell." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Draught of Might", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Strength checks and Strength saves for 1 minute (1 turn)." } },
    { id: nextId(), name: "Elixir of Keen Sight", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Wisdom (Perception) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Elixir of Keen Sight", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Wisdom (Perception) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Elixir of Keen Sight", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Gain advantage on Wisdom (Perception) checks for 1 minute (1 turn)." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Elixir of Restoration", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "4d4+4", target: "any-explorer", description: "Restore 4d4 + 4 HP." } },
    { id: nextId(), name: "Purifying Draught", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Cure the Poisoned condition." } },
    { id: nextId(), name: "Purifying Draught", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Cure the Poisoned condition." } },
    { id: nextId(), name: "Purifying Draught", type: "Potion", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Cure the Poisoned condition." } },
    { id: nextId(), name: "Sovereign Salve", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8", target: "any-explorer", description: "Restore 1d8 HP." } },
    { id: nextId(), name: "Sovereign Salve", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8", target: "any-explorer", description: "Restore 1d8 HP." } },
    { id: nextId(), name: "Sovereign Salve", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8", target: "any-explorer", description: "Restore 1d8 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Vial of Vitality", type: "Potion", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "2d4+2", target: "any-explorer", description: "Restore 2d4 + 2 HP." } },
    { id: nextId(), name: "Scroll of Arcane Insight", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Reveals the magical properties of one item. Consumed on use." } },
    { id: nextId(), name: "Scroll of Arcane Insight", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Reveals the magical properties of one item. Consumed on use." } },
    { id: nextId(), name: "Scroll of Arcane Insight", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Reveals the magical properties of one item. Consumed on use." } },
    { id: nextId(), name: "Scroll of Grasping Vines", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Grasping Vines spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Grasping Vines", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Grasping Vines spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Grasping Vines", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Grasping Vines spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Healing Touch", type: "Scroll", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8+5", target: "any-explorer", description: "Allows the user to cast the Healing Touch spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Healing Touch", type: "Scroll", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8+5", target: "any-explorer", description: "Allows the user to cast the Healing Touch spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Healing Touch", type: "Scroll", class: "Any", category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8+5", target: "any-explorer", description: "Allows the user to cast the Healing Touch spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Illusory Doubles", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Illusory Doubles spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Illusory Doubles", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Illusory Doubles spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Illusory Doubles", type: "Scroll", class: "Any", category: "Utility", apCost: 1, effect: { type: "utility", description: "Allows the user to cast the Illusory Doubles spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Inferno Sphere", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "8d6", target: "any-monster", description: "Allows the user to cast the Inferno Sphere spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Inferno Sphere", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "8d6", target: "any-monster", description: "Allows the user to cast the Inferno Sphere spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Inferno Sphere", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "8d6", target: "any-monster", description: "Allows the user to cast the Inferno Sphere spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Shockwave", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d8", target: "any-monster", description: "Allows the user to cast the Shockwave spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Shockwave", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d8", target: "any-monster", description: "Allows the user to cast the Shockwave spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Scroll of Shockwave", type: "Scroll", class: "Any", category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d8", target: "any-monster", description: "Allows the user to cast the Shockwave spell as if they were a spellcaster. Consumed on use." } },
    { id: nextId(), name: "Climber's Spikes", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "A set of metal spikes and a hammer used to create hand/foot holds on difficult surfaces. Provides advantage on difficult Strength (Athletics) or Dexterity (Acrobatics) checks for climbing on rock, ice, or rough walls." } },
    { id: nextId(), name: "Climber's Spikes", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "A set of metal spikes and a hammer used to create hand/foot holds on difficult surfaces. Provides advantage on difficult Strength (Athletics) or Dexterity (Acrobatics) checks for climbing on rock, ice, or rough walls." } },
    { id: nextId(), name: "Climber's Spikes", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "A set of metal spikes and a hammer used to create hand/foot holds on difficult surfaces. Provides advantage on difficult Strength (Athletics) or Dexterity (Acrobatics) checks for climbing on rock, ice, or rough walls." } },
    { id: nextId(), name: "Climbing Hook", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used with a rope for ascending or descending. Provides advantage on Strength (Athletics) checks for climbing difficult surfaces." } },
    { id: nextId(), name: "Climbing Hook", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used with a rope for ascending or descending. Provides advantage on Strength (Athletics) checks for climbing difficult surfaces." } },
    { id: nextId(), name: "Climbing Hook", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used with a rope for ascending or descending. Provides advantage on Strength (Athletics) checks for climbing difficult surfaces." } },
    { id: nextId(), name: "Consecrated Emblem", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used as a focus for casting certain spells. May have other minor effects when interacting with undead or evil entities (GM's discretion)." } },
    { id: nextId(), name: "Consecrated Emblem", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used as a focus for casting certain spells. May have other minor effects when interacting with undead or evil entities (GM's discretion)." } },
    { id: nextId(), name: "Consecrated Emblem", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used as a focus for casting certain spells. May have other minor effects when interacting with undead or evil entities (GM's discretion)." } },
    { id: nextId(), name: "Iron Pry", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Strength checks made to force open doors, chests, or containers." } },
    { id: nextId(), name: "Iron Pry", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Strength checks made to force open doors, chests, or containers." } },
    { id: nextId(), name: "Iron Pry", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Strength checks made to force open doors, chests, or containers." } },
    { id: nextId(), name: "Lockpicks & Shims", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Skill Challenges related to picking locks or disarming simple traps." } },
    { id: nextId(), name: "Lockpicks & Shims", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Skill Challenges related to picking locks or disarming simple traps." } },
    { id: nextId(), name: "Lockpicks & Shims", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Provides advantage on Skill Challenges related to picking locks or disarming simple traps." } },
    { id: nextId(), name: "Spark & Steel", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Allows the user to light fires or other flammable objects quickly. Can be used in Skill Challenges related to survival or setting fires." } },
    { id: nextId(), name: "Spark & Steel", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Allows the user to light fires or other flammable objects quickly. Can be used in Skill Challenges related to survival or setting fires." } },
    { id: nextId(), name: "Spark & Steel", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Allows the user to light fires or other flammable. Can be used in Skill Challenges related to survival or setting fires." } },
    { id: nextId(), name: "Sturdy Cord (50 ft)", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used for climbing, tying, or other tasks requiring rope. Useful in Skill Challenges (Strength or Dexterity based)." } },
    { id: nextId(), name: "Sturdy Cord (50 ft)", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used for climbing, tying, or other tasks requiring rope. Useful in Skill Challenges (Strength or Dexterity based)." } },
    { id: nextId(), name: "Sturdy Cord (50 ft)", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Can be used for climbing, tying, or other tasks requiring rope. Useful in Skill Challenges (Strength or Dexterity based)." } },
    { id: nextId(), name: "Trail Digger", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Useful for digging. Provides advantage on Skill Challenges related to excavation or creating simple earthworks." } },
    { id: nextId(), name: "Trail Digger", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Useful for digging. Provides advantage on Skill Challenges related to excavation or creating simple earthworks." } },
    { id: nextId(), name: "Trail Digger", type: "Utility", class: "Any", category: "Utility", apCost: 0, effect: { type: "utility", description: "Useful for digging. Provides advantage on Skill Challenges related to excavation or creating simple earthworks." } },
];

const spellCards = [
    { id: nextId(), name: "Acid Burst", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d6", target: "any-monster", description: "Deals 1d6 acid damage to each creature in a 5-foot radius sphere." } },
    { id: nextId(), name: "Acid Burst", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d6", target: "any-monster", description: "Deals 1d6 acid damage to each creature in a 5-foot radius sphere." } },
    { id: nextId(), name: "Cinder Shot", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d10", target: "any-monster", description: "Deals 1d10 fire damage." } },
    { id: nextId(), name: "Cinder Shot", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d10", target: "any-monster", description: "Deals 1d10 fire damage." } },
    { id: nextId(), name: "Flame Fan", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "3d6", target: "any-monster", description: "Deals 3d6 fire damage in a 15-foot cone. Dexterity saving throw (DC 13) for half damage." } },
    { id: nextId(), name: "Flame Fan", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "3d6", target: "any-monster", description: "Deals 3d6 fire damage in a 15-foot cone. Dexterity saving throw (DC 13) for half damage." } },
    { id: nextId(), name: "Force Barrier", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", status: "Guarded", duration: 2, target: "self", description: "Until the start of your next turn, increase your Shield Points by 5." } },
    { id: nextId(), name: "Force Barrier", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", status: "Guarded", duration: 2, target: "self", description: "Until the start of your next turn, increase your Shield Points by 5." } },
    { id: nextId(), name: "Force Darts", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d4+1", target: "any-monster", description: "Deals 1d4 + 1 force damage to up to three targets." } },
    { id: nextId(), name: "Force Darts", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d4+1", target: "any-monster", description: "Deals 1d4 + 1 force damage to up to three targets." } },
    { id: nextId(), name: "Frost Beam", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d8", status: "Slowed", duration: 1, target: "any-monster", description: "Deals 1d8 cold damage and reduces target's speed by 10 feet until the start of your next turn." } },
    { id: nextId(), name: "Frost Beam", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d8", status: "Slowed", duration: 1, target: "any-monster", description: "Deals 1d8 cold damage and reduces target's speed by 10 feet until the start of your next turn." } },
    { id: nextId(), name: "Grasping Vines", type: "Spell", class: ["Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Restrains creatures in a 20-foot square. Strength saving throw (DC 13)." } },
    { id: nextId(), name: "Grasping Vines", type: "Spell", class: ["Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Restrains creatures in a 20-foot square. Strength saving throw (DC 13)." } },
    { id: nextId(), name: "Healing Touch", type: "Spell", class: ["Cleric", "Ranger"], category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8+5", target: "any-explorer", description: "Heals 1d8 + 5 HP." } },
    { id: nextId(), name: "Healing Touch", type: "Spell", class: ["Cleric", "Ranger"], category: "Healing", apCost: 1, effect: { type: "heal", dice: "1d8+5", target: "any-explorer", description: "Heals 1d8 + 5 HP." } },
    { id: nextId(), name: "Illumination", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Object emits bright light in a 20-foot radius and dim light for an additional 20 feet." } },
    { id: nextId(), name: "Illumination", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Object emits bright light in a 20-foot radius and dim light for an additional 20 feet." } },
    { id: nextId(), name: "Inspire Allies", type: "Spell", class: ["Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", target: "all-explorers", statusToApply: { name: 'Inspired', type: 'stat_modifier', bonuses: { damageBonus: 2 }, duration: 2 }, description: "All explorers gain a +2 bonus to their attack rolls for 1 round." } },
    { id: nextId(), name: "Inspire Allies", type: "Spell", class: ["Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", target: "all-explorers", statusToApply: { name: 'Inspired', type: 'stat_modifier', bonuses: { damageBonus: 2 }, duration: 2 }, description: "All explorers gain a +2 bonus to their attack rolls for 1 round." } },
    { id: nextId(), name: "Jolt Touch", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d8", target: "any-monster", description: "Deals 1d8 lightning damage. Target can't take reactions until the start of its next turn." } },
    { id: nextId(), name: "Jolt Touch", type: "Spell", class: ["Mage"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d8", target: "any-monster", description: "Deals 1d8 lightning damage. Target can't take reactions until the start of its next turn." } },
    { id: nextId(), name: "Obscuring Mist", type: "Spell", class: ["Mage", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Creates a 20-foot radius sphere of fog that heavily obscures vision." } },
    { id: nextId(), name: "Obscuring Mist", type: "Spell", class: ["Mage", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Creates a 20-foot radius sphere of fog that heavily obscures vision." } },
    { id: nextId(), name: "Radiant Strike", type: "Spell", class: ["Cleric"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "4d6", target: "any-monster", description: "Deals 4d6 radiant damage. The next attack roll against the target has advantage." } },
    { id: nextId(), name: "Radiant Strike", type: "Spell", class: ["Cleric"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "4d6", target: "any-monster", description: "Deals 4d6 radiant damage. The next attack roll against the target has advantage." } },
    { id: nextId(), name: "Restore Form", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Repairs a single break or tear in an object." } },
    { id: nextId(), name: "Restore Form", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Repairs a single break or tear in an object." } },
    { id: nextId(), name: "Restore Form", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Repairs a single break or tear in an object." } },
    { id: nextId(), name: "Restore Form", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Repairs a single break or tear in an object." } },
    { id: nextId(), name: "Restore Form", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Repairs a single break or tear in an object." } },
    { id: nextId(), name: "Shockwave", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d8", target: "any-monster", description: "Deals 2d8 thunder damage and pushes creatures 10 feet away. Constitution saving throw (DC 13)." } },
    { id: nextId(), name: "Shockwave", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "2d8", target: "any-monster", description: "Deals 2d8 thunder damage and pushes creatures 10 feet away. Constitution saving throw (DC 13)." } },
    { id: nextId(), name: "Skill Boon", type: "Spell", class: ["Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Target gains 1d4 bonus to one ability check." } },
    { id: nextId(), name: "Skill Boon", type: "Spell", class: ["Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Target gains 1d4 bonus to one ability check." } },
    { id: nextId(), name: "Slumber Wave", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Up to 5d8 hit points of creatures fall unconscious." } },
    { id: nextId(), name: "Slumber Wave", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Up to 5d8 hit points of creatures fall unconscious." } },
    { id: nextId(), name: "Spectral Grasp", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Create a spectral, floating hand that can manipulate objects." } },
    { id: nextId(), name: "Spectral Grasp", type: "Spell", class: ["Mage"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Create a spectral, floating hand that can manipulate objects." } },
    { id: nextId(), name: "Toxic Cloud", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d12", status: "Poisoned", duration: 2, target: "any-monster", description: "Deals 1d12 poison damage. Constitution saving throw (DC 13)." } },
    { id: nextId(), name: "Toxic Cloud", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 1, effect: { type: "damage", dice: "1d12", status: "Poisoned", duration: 2, target: "any-monster", description: "Deals 1d12 poison damage. Constitution saving throw (DC 13)." } },
    { id: nextId(), name: "Warding Touch", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Target gains 1d4 bonus to one saving throw." } },
    { id: nextId(), name: "Warding Touch", type: "Spell", class: ["Mage", "Cleric", "Ranger"], category: "Utility", apCost: 1, effect: { type: "utility", description: "Target gains 1d4 bonus to one saving throw." } },
    { id: nextId(), name: "Illusory Doubles", type: "Spell", class: ["Mage"], category: "Utility", apCost: 2, effect: { type: "utility", description: "Creates three illusory duplicates of yourself." } },
    { id: nextId(), name: "Immobilize Foe", type: "Spell", class: ["Mage", "Cleric"], category: "Utility", apCost: 2, effect: { type: "utility", status: "Stunned", statusType: "stun", duration: 2, target: "any-monster", description: "A humanoid must make a Wisdom saving throw (DC 13) or be paralyzed." } },
    { id: nextId(), name: "Inferno Rays", type: "Spell", class: ["Mage"], category: "Damage", apCost: 2, effect: { type: "damage", dice: "2d6", target: "any-monster", description: "You create three rays of fire and hurl them at targets within range. Each ray deals 2d6 fire damage." } },
    { id: nextId(), name: "Lunar Ray", type: "Spell", class: ["Cleric", "Ranger"], category: "Damage", apCost: 2, effect: { type: "damage", dice: "2d10", target: "any-monster", description: "Deals 2d10 radiant damage to any creature that enters the beam or starts its turn there." } },
    { id: nextId(), name: "Mind Scan", type: "Spell", class: ["Mage"], category: "Utility", apCost: 2, effect: { type: "utility", description: "Allows you to read the surface thoughts of creatures within 30 feet." } },
    { id: nextId(), name: "Sonic Burst", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 2, effect: { type: "damage", dice: "3d8", target: "any-monster", description: "Deals 3d8 thunder damage to creatures in a 10-foot radius sphere. Constitution saving throw (DC 14) for half damage." } },
    { id: nextId(), name: "Sticky Webbing", type: "Spell", class: ["Mage", "Ranger"], category: "Utility", apCost: 2, effect: { type: "utility", status: "Slowed", duration: 3, target: "any-monster", description: "Creates a large mass of thick, sticky webbing. Creatures in the webs are restrained." } },
    { id: nextId(), name: "Umbral Sphere", type: "Spell", class: ["Mage"], category: "Utility", apCost: 2, effect: { type: "utility", description: "Creates a 15-foot radius sphere of darkness that heavily obscures vision." } },
    { id: nextId(), name: "Vanish", type: "Spell", class: ["Mage", "Ranger"], category: "Utility", apCost: 2, effect: { type: "utility", description: "Makes a creature invisible." } },
    { id: nextId(), name: "Wind Blast", type: "Spell", class: ["Ranger"], category: "Utility", apCost: 2, effect: { type: "utility", description: "Blows a 60-foot line of wind, creatures in the line must make a Strength saving throw (DC 13) or be pushed 15 feet." } },
    { id: nextId(), name: "Abolish Magic", type: "Spell", class: ["Mage", "Cleric"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Ends one spell on a creature or object." } },
    { id: nextId(), name: "Accelerate", type: "Spell", class: ["Mage"], category: "Utility", apCost: 3, effect: { type: "utility", description: "A creature gains increased speed, +2 to AC, advantage on Dexterity saving throws, and one extra action on each of its turns." } },
    { id: nextId(), name: "Aquatic Adaptation", type: "Spell", class: ["Cleric", "Ranger"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Gives creatures the ability to breathe underwater." } },
    { id: nextId(), name: "Captivating Display", type: "Spell", class: ["Mage", "Cleric"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Creatures in a 30-foot cube become charmed if they fail a Wisdom saving throw (DC 14)." } },
    { id: nextId(), name: "Decelerate", type: "Spell", class: ["Mage"], category: "Utility", apCost: 3, effect: { type: "utility", status: "Slowed", duration: 2, target: "any-monster", description: "Up to six creatures have their speed halved, -2 to AC, and can only take either an action or a bonus action on their turn." } },
    { id: nextId(), name: "Grand Illusion", type: "Spell", class: ["Mage"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Creates the illusion of an object, creature, or other visible phenomenon that is no larger than a 20-foot cube." } },
    { id: nextId(), name: "Inferno Sphere", type: "Spell", class: ["Mage"], category: "Damage", apCost: 3, effect: { type: "damage", dice: "8d6", target: "any-monster", description: "Deals 8d6 fire damage to creatures in a 20-foot radius sphere. Dexterity saving throw (DC 15) for half damage." } },
    { id: nextId(), name: "Magic Negation", type: "Spell", class: ["Mage", "Cleric"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Attempts to negate another spell." } },
    { id: nextId(), name: "Thunder Stroke", type: "Spell", class: ["Mage", "Ranger"], category: "Damage", apCost: 3, effect: { type: "damage", dice: "8d6", target: "any-monster", description: "A crackling bolt of lightning strikes, leaving a trail of ozone in the air." } },
    { id: nextId(), name: "Winged Ascent", type: "Spell", class: ["Mage", "Cleric"], category: "Utility", apCost: 3, effect: { type: "utility", description: "Gives a creature a flying speed of 60 feet." } },
];

const monsterCards = [
    { id: nextId(), name: "Phantom Light", type: "Monster", maxHp: 5, requiredRollToHit: 12, attackBonus: 0, ap: 1, effect: { type: "damage", dice: "1d8", description: "Incorporeal Movement (Can move through other creatures and objects.). Proximity damage." } },
    { id: nextId(), name: "Ember Flicker", type: "Monster", maxHp: 6, requiredRollToHit: 12, attackBonus: 4, ap: 2, effect: { type: "damage", dice: "1d10", description: "On miss: Lights flammable object / Ignite (DC 12 DEX save or catch fire, 1d4 fire/turn)." } },
    { id: nextId(), name: "Pestie Prowler", type: "Monster", maxHp: 7, requiredRollToHit: 10, attackBonus: 8, ap: 2, effect: { type: "damage", dice: "1d6", description: "Sneaky Escape — Dex roll (DC 12) to flee if ≤ 3 HP." } },
    { id: nextId(), name: "Pestie Pilferer", type: "Monster", maxHp: 8, requiredRollToHit: 12, attackBonus: 4, ap: 2, effect: { type: "damage", dice: "1d6+2", description: "Quick Feet (Can Break Away as a bonus action.)." } },
    { id: nextId(), name: "Grotto Weaver", type: "Monster", maxHp: 10, requiredRollToHit: 12, attackBonus: 6, ap: 2, effect: { type: "damage", dice: "1d6", description: "Web Shot — Can attempt to restrain a player with a web (DC 10 Strength save to escape)." } },
    { id: nextId(), name: "Flutterwing Swarm", type: "Monster", maxHp: 10, requiredRollToHit: 12, attackBonus: 4, ap: 2, effect: { type: "damage", dice: "2d4", description: "Blind Flight (Immune to blindness conditions.)." } },
    { id: nextId(), name: "Pestie Whisperer", type: "Monster", maxHp: 10, requiredRollToHit: 12, attackBonus: 3, ap: 2, effect: { type: "damage", dice: "1d4", description: "Tribal Magic (Once per combat, +2 attack rolls for all pesties within 20 ft for 1 round.)" } },
    { id: nextId(), name: "Scale-kin Skulker", type: "Monster", maxHp: 10, requiredRollToHit: 12, attackBonus: 2, ap: 2, effect: { type: "damage", dice: "1d4+1", description: "Trap Master (Sets a trap at start of combat. DC 10 Perception/DC 12 Dex save to avoid, 1d4 piercing)." } },
    { id: nextId(), name: "Essence Thief", type: "Monster", maxHp: 15, requiredRollToHit: 12, attackBonus: 4, ap: 2, effect: { type: "damage", dice: "2d6", description: "Incorporeal (Can move through solid objects.)." } },
    { id: nextId(), name: "Bone Archer", type: "Monster", maxHp: 18, requiredRollToHit: 12, attackBonus: 3, ap: 2, effect: { type: "damage", dice: "1d8", description: "Bone Resilience (Immune to poison and charm.)." } },
    { id: nextId(), name: "Veiled Fanatic", type: "Monster", maxHp: 20, requiredRollToHit: 12, attackBonus: 5, ap: 2, effect: { type: "damage", dice: "1d4+3", description: "Unholy Fervor (Can re-roll a failed saving throw once per fight.)." } },
    { id: nextId(), name: "Striped Marauder", type: "Monster", maxHp: 23, requiredRollToHit: 12, attackBonus: 4, ap: 3, effect: { type: "damage", dice: "1d8+2", description: "Rampage (When reduces creature to 0 HP with melee attack on turn, move half speed and make another attack.)" } },
    { id: nextId(), name: "Segmented Horror", type: "Monster", maxHp: 24, requiredRollToHit: 12, attackBonus: 5, ap: 3, effect: { type: "damage", dice: "1d4+3", description: "Wall Climber (Can move across walls and ceilings.)." } },
    { id: nextId(), name: "Stonegaze Wyrmlet (Young)", type: "Monster", maxHp: 24, requiredRollToHit: 12, attackBonus: 4, ap: 3, effect: { type: "damage", dice: "1d6+2", description: "Petrification Gaze (DC 12 CON save or petrified)" } },
    { id: nextId(), name: "Caustic Sludge", type: "Monster", maxHp: 24, requiredRollToHit: 12, attackBonus: 3, ap: 2, effect: { type: "damage", dice: "1d8", description: "Split on Lightning (Splits into two smaller oozes if hit by lightning.)." } },
    { id: nextId(), name: "Sky Lurer", type: "Monster", maxHp: 27, requiredRollToHit: 12, attackBonus: 4, ap: 3, effect: { type: "damage", dice: "1d6+1", description: "Swooping Attack (Move up to 40 ft and attack as part of same action.)." } },
    { id: nextId(), name: "Highway Scourge", type: "Monster", maxHp: 28, requiredRollToHit: 12, attackBonus: 6, ap: 3, effect: { type: "damage", dice: "2d6+3", description: "Bonus Action: Shout (All Bandits get +1 attack for one round.) / Tactical Strike (Command ally attack once/fight)" } },
    { id: nextId(), name: "Ruined Sentinel", type: "Monster", maxHp: 33, requiredRollToHit: 13, attackBonus: 6, ap: 3, effect: { type: "damage", dice: "2d8", description: "Magic Resistance (Advantage on saving throws against spells.)." } },
    { id: nextId(), name: "Shadowmaw Alpha", type: "Monster", maxHp: 34, requiredRollToHit: 13, attackBonus: 5, ap: 3, effect: { type: "damage", dice: "2d6+2", description: "Pack Tactics (Advantage on attacks if ally is adjacent to target.)." } },
    { id: nextId(), name: "Stone Wing", type: "Monster", maxHp: 35, requiredRollToHit: 13, attackBonus: 5, ap: 3, effect: { type: "damage", dice: "1d6+3", description: "Stone Form (Can become indistinguishable from statue. Advantage on Dexterity (Stealth) in stone form.)." } },
    { id: nextId(), name: "Haunted Cuirass", type: "Monster", maxHp: 41, requiredRollToHit: 13, attackBonus: 4, ap: 3, effect: { type: "damage", dice: "2d6", description: "Unyielding Form (Immune to poison, exhaustion, and fear.)." } },
    { id: nextId(), name: "Greenskin Mauler", type: "Monster", maxHp: 44, requiredRollToHit: 14, attackBonus: 5, ap: 3, effect: { type: "damage", dice: "1d12+3", description: "Relentless Endurance (Once/day, if reduced to 0 HP, drop to 1 HP instead.)." } },
    { id: nextId(), name: "Spectral Corruptor", type: "Monster", maxHp: 45, requiredRollToHit: 14, attackBonus: 6, ap: 3, effect: { type: "damage", dice: "3d6", description: "Incorporeal Passage (Can move through solid objects.)." } },
    { id: nextId(), name: "Axehorn Brute", type: "Monster", maxHp: 55, requiredRollToHit: 14, attackBonus: 7, ap: 4, effect: { type: "damage", dice: "2d12+4", description: "Labyrinthine Recall (Cannot become lost; always knows the shortest path to any location.)." } },
    { id: nextId(), name: "Briar Witch", type: "Monster", maxHp: 59, requiredRollToHit: 14, attackBonus: 5, ap: 4, effect: { type: "damage", dice: "2d6", description: "Cackle of Madness (Once per fight, confuse all enemies within 30 ft for 1 turn.)." } },
    { id: nextId(), name: "Wrapped Ancient", type: "Monster", maxHp: 60, requiredRollToHit: 14, attackBonus: 5, ap: 4, effect: { type: "damage", dice: "2d6+3", description: "Undead Fortitude (If damage reduces to 0 HP, CON save vs 5+damage unless radiant/crit. On success, drops to 1 HP.)." } },
    { id: nextId(), name: "Watery Charmer", type: "Monster", maxHp: 63, requiredRollToHit: 14, attackBonus: 6, ap: 4, effect: { type: "damage", dice: "1d6+3", description: "Captivating Song (Creatures within 30 feet must make a DC 13 Wisdom saving throw or be charmed.)." } },
    { id: nextId(), name: "Hill Oaf", type: "Monster", maxHp: 64, requiredRollToHit: 15, attackBonus: 6, ap: 4, effect: { type: "damage", dice: "2d8+4", description: "Powerful Blow (Once per turn, can add +2 to the damage roll.)." } },
    { id: nextId(), name: "Deathlord Marshal", type: "Monster", maxHp: 78, requiredRollToHit: 15, attackBonus: 7, ap: 4, effect: { type: "damage", dice: "3d6+4", description: "Unholy Endurance (When reduced to 0 HP, roll DC 15 CON save — if successful, rise with 10 HP.)." } },
    { id: nextId(), name: "Earth Colossus", type: "Monster", maxHp: 112, requiredRollToHit: 16, attackBonus: 8, ap: 5, effect: { type: "damage", dice: "2d10+5", description: "Immutable Form (Immune to poison, exhaustion, and petrification.)." } },
    { id: nextId(), name: "Winter Juggernaut", type: "Monster", maxHp: 130, requiredRollToHit: 17, attackBonus: 9, ap: 5, effect: { type: "damage", dice: "3d12+6", description: "Icy Aura (Deals 1d4 cold damage to any creature starting its turn within 5 feet.)." } },
    { id: nextId(), name: "Hellfire Sovereign", type: "Monster", maxHp: 195, requiredRollToHit: 18, attackBonus: 9, ap: 6, effect: { type: "damage", dice: "4d6+5", description: "Hellish Regeneration (Regains 10 HP at start of turn unless hit by radiant.) / Flaming Aura (1d6 fire to enemies starting turn within 5 ft)" } },
    { id: nextId(), name: "Rotwood Behemoth", type: "Monster", maxHp: 214, requiredRollToHit: 18, attackBonus: 8, ap: 6, effect: { type: "damage", dice: "3d8+4", description: "Rooted Horror (30 ft radius difficult terrain.) / Corruption Pulse (Once/battle, 20 ft pulse, DC 15 CON save vs 2d8 necrotic)" } },
];

const weaponCards = [
    { id: nextId(), name: "Shortsword", type: "Weapon", class: ["Rogue", "Warrior", "Ranger"], apCost: 2, effect: { type: "damage", dice: "1d6" } },
    { id: nextId(), name: "Dagger", type: "Weapon", class: ["Rogue", "Mage", "Ranger"], apCost: 2, effect: { type: "damage", dice: "1d4" } },
    { id: nextId(), name: "Greatsword", type: "Weapon", class: ["Warrior", "Barbarian"], apCost: 2, effect: { type: "damage", dice: "2d6" } },
    { id: nextId(), name: "Handaxe", type: "Weapon", class: ["Barbarian", "Warrior", "Ranger"], apCost: 2, effect: { type: "damage", dice: "1d6" } },
    { id: nextId(), name: "Longbow", type: "Weapon", class: ["Ranger"], apCost: 2, effect: { type: "damage", dice: "1d8" } },
    { id: nextId(), name: "Warhammer", type: "Weapon", class: ["Warrior", "Cleric", "Barbarian"], apCost: 2, effect: { type: "damage", dice: "1d8" } },
    { id: nextId(), name: "Staff of the Magi", type: "Weapon", class: ["Mage", "Cleric"], apCost: 2, effect: { type: "damage", dice: "1d6", bonuses: { damageBonus: 2, shieldBonus: 1 } } },
    { id: nextId(), name: "Sun Blade", type: "Weapon", class: ["Cleric", "Warrior", "Ranger"], apCost: 2, effect: { type: "damage", dice: "1d8", bonuses: { damageBonus: 2 } } },
    { id: nextId(), name: "Vorpal Sword", type: "Weapon", class: ["Warrior", "Barbarian", "Rogue"], apCost: 2, effect: { type: "damage", dice: "1d10", bonuses: { damageBonus: 3 } } },
];

const armorCards = [
    { id: nextId(), name: "Leather Armor", type: "Armor", class: ["Rogue", "Ranger", "Barbarian"], effect: { bonuses: { shieldBonus: 1 } } },
    { id: nextId(), name: "Chain Mail", type: "Armor", class: ["Warrior", "Cleric"], effect: { bonuses: { shieldBonus: 3 } } },
    { id: nextId(), name: "Plate Armor", type: "Armor", class: ["Warrior", "Cleric"], effect: { bonuses: { shieldBonus: 5 } } },
    { id: nextId(), name: "Shield of Faith", type: "Armor", class: ["Cleric"], effect: { bonuses: { shieldBonus: 2, hp: 5 } } },
    { id: nextId(), name: "Dragon Scale Mail", type: "Armor", class: ["Warrior", "Ranger"], effect: { bonuses: { shieldBonus: 4, damageBonus: 1 } } },
];

const worldEventCards = [
    { id: nextId(), name: "Echoes of the Past", type: "World Event", tags: "Mental / Arcane", description: "A wave of psychic energy washes over the area, forcing visions of a past battle into everyone's minds.", saveInfo: { save: "Wisdom", dc: 14, effectOnFail: "Stunned for 1 round" } },
    { id: nextId(), name: "Wild Magic Surge", type: "World Event", tags: "Arcane / Environmental", description: "The fabric of magic tears. Random, unpredictable effects manifest around the party.", saveInfo: { save: "None", dc: 0, effectOnFail: "" } },
];

const playerEventCards = [
    { id: nextId(), name: "Sudden Insight", type: "Player Event", outcome: "You notice a hidden detail in your surroundings, granting you an advantage on your next skill-based action.", effect: { name: 'Advantage', type: 'stat_modifier', bonuses: { }, duration: 2 } },
    { id: nextId(), name: "Twisted Ankle", type: "Player Event", outcome: "You misstep on the uneven ground, twisting your ankle.", effect: { name: 'Slowed', type: 'stat_modifier', bonuses: { ap: -1 }, duration: 2 } },
];

const discoveryCards = [
    { id: nextId(), name: "Cryptic Map", type: "Discovery", description: "A piece of a map, showing a location you don't recognize." },
    { id: nextId(), name: "Forgotten Idol", type: "Discovery", description: "A small, strange idol made of an unknown, oily black stone." },
];

module.exports = {
  classes,
  itemCards,
  spellCards,
  monsterCards,
  weaponCards,
  armorCards,
  worldEventCards,
  playerEventCards,
  discoveryCards,
  statusEffectDefinitions,
  npcDialogue,
  skillChallenges,
  actionCosts,
};